# Generated by Django 4.1 on 2022-08-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(null=True, to='app.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
