# Generated by Django 4.1 on 2022-08-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dish_image_alter_dish_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(to='app.ingredient'),
        ),
    ]
