# Generated by Django 4.1 on 2022-08-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dish_image_alter_ingredient_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='sauce',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
